variables:
  var_a: 1
  var_b: 2

gateways:
  local:
    connection:
      type: duckdb
      database: db.db
  snowflake:
    variables:
      var_a: 3
    connection:
      type: snowflake
      account: dktssnk-bb94975
      user: SPARE
      # password: {{ env_var('SNOWFLAKE_PASSWORD') }}
      password: Azam@123
      database: SQLMESH_DEMO
      warehouse: COMPUTE_WH
    test_connection:
      type: snowflake
      account: dktssnk-bb94975
      user: SPARE
      # password: {{ env_var('SNOWFLAKE_PASSWORD') }}
      password: Azam@123
      database: SQLMESH_DEMO
      warehouse: COMPUTE_WH
  
  # databricks:
  #   connection:
  #     type: databricks
  #     server_hostname: ""
  #     http_path: ""
  #     access_token: ""

default_gateway: snowflake

model_defaults:
  dialect: snowflake
  start: 2024-11-19
